server:
  port: 8099
spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true